config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :categories, except: [:edit, :update, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :recipe_id, uniqueness: {scope: :category_id}
  validates :comment, length: { minimum: 6 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, numericality: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark =  Bookmark.new(bookmark_params)
    @bookmark.category = @category

    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a recipe to <%= @category.name %> category</h1>

<%= simple_form_for [@category, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :recipe %>
  <%= f.submit %>
<% end %>

<%= link_to "Back", category_path(@category.id) %>

app/views/categories/index.html.erb
<div class="banner" style="background-image: url(<%= image_path 'banner.png' %>)">
    <div>
      <h1>Cookbook</h1>
      <h3>Save your favourite recipes</h3>
    </div>
</div>

<div class="container">
  <div class = "info-top">
    <h2>List of Categories</h2>
  <%= link_to "New Category", new_category_path, class: "btn custom-btn text-white" %>
  </div>

  <div class="cards">
    <% @categories.each do |category| %>

    <%= link_to category_path(category) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
          <div>
            <h3><%= category.name %></h3>
            <p><%= category.bookmarks.count %> recipes</p>
          </div>
      </div>
      <% end %>

    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>Create a new category</h1>

<%= simple_form_for @category do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

<%= link_to "Back", categories_path %>

app/views/categories/show.html.erb
<div class="banner" style="background-image: url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <div>
      <h1><%= @category.name %> </h1>
    </div>
</div>

<div class="container">
  <div class = "info-top">
    <h2>Recipes </h2>
    <%= link_to "Add recipe", new_category_bookmark_path(@category), class: "btn btn-dark text-white" %>
  </div>

  <div class="cards">
    <% @category.bookmarks.each do |bookmark| %>
      <div class="card-trip">
        <img src="<%= bookmark.recipe.image_url %>" />
        <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn-delete" do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>

        <div class="card-trip-description">
          <h3><%= bookmark.recipe.name %></h3>
          <p><%= bookmark.recipe.description.truncate(100) %></p>
        </div>

        <div class="card-trip-infos">
          <p><%= bookmark.comment %></p>

          <%= bookmark.recipe.rating %> <%= "⭐" * bookmark.recipe.rating.floor%>

        </div>

      </div>
    <% end %>
  </div>

</div>

<%= link_to "Add recipe", new_category_bookmark_path(@category.id) %>

<%= link_to "Back", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= image_tag 'cookbook.png' %>

   <div>
    <%= link_to "Home" %>
    <%= link_to "New Category" %>
  </div>

</div>